


PROGRAM MAIN
USE KINDS,   ONLY: dp, i4
USE GLOBALS, ONLY: pi
USE TESTS,   ONLY: &
  TEST1_ANALYTIC, TEST1_VSH, TEST1_GW, &
  TEST2_ANALYTIC, TEST2_VSH, TEST2_GW, &
  BATCH_ALM_CONS, BATCH_DALM_CONS, BATCH_SSH_CONS, &
  SSH_ORTHO, BATCH_GRAD_SSH_CONS, BATCH_L_SSH_CONS, &
  BATCH_PVSH_RAD_CONS, BATCH_PVSH_POL_CONS, BATCH_PVSH_TOR_CONS, &
  BATCH_VSH_TOR_CONS, BATCH_VSH_POL_UP_CONS, BATCH_VSH_POL_DN_CONS, &
  PVSH_POL_TOR_ORTHO, VSH_POL_INVERSION
IMPLICIT NONE

INTEGER(KIND=i4) :: NTHETA, I
PARAMETER (NTHETA=100)
COMPLEX(KIND=dp), DIMENSION(NTHETA) :: TEST1A,TEST1B,TEST1C
COMPLEX(KIND=dp), DIMENSION(NTHETA) :: TEST2A,TEST2B,TEST2C

TEST1A = TEST1_ANALYTIC(NTHETA)
TEST1B = TEST1_VSH(NTHETA)
TEST1C = TEST1_GW(NTHETA)

TEST2A = TEST2_ANALYTIC(NTHETA)
TEST2B = TEST2_VSH(NTHETA)
TEST2C = TEST2_GW(NTHETA)

OPEN(UNIT=11, FILE="./validation/TEST1.dat")
OPEN(UNIT=12, FILE="./validation/TEST2.dat")

DO I=1,NTHETA
  WRITE(11,*) (I-1)*pi/(NTHETA-1),TEST1A(I),TEST1B(I),TEST1C(I)
ENDDO

DO I=1,NTHETA
  WRITE(12,*) (I-1)*pi/(NTHETA-1),TEST2A(I),TEST2B(I),TEST2C(I)
ENDDO

CLOSE(11)
CLOSE(12)

OPEN(UNIT=21, FILE="./validation/batch_alm_cons.dat")
CALL BATCH_ALM_CONS(8, 20, 21)
CLOSE(21)

OPEN(UNIT=22, FILE="./validation/batch_dalm_cons.dat")
CALL BATCH_DALM_CONS(8, 20, 22)
CLOSE(22)

OPEN(UNIT=23, FILE="./validation/batch_ssh_cons.dat")
CALL BATCH_SSH_CONS(5, 15, 23)
CLOSE(23)

OPEN(UNIT=24, FILE="./validation/ssh_ortho.dat")
CALL SSH_ORTHO(6, 10000, 24)
CLOSE(24)

OPEN(UNIT=31, FILE="./validation/batch_grad_ssh_cons.dat")
CALL BATCH_GRAD_SSH_CONS(5, 15, 31)
CLOSE(31)

OPEN(UNIT=32, FILE="./validation/batch_l_ssh_cons.dat")
CALL BATCH_L_SSH_CONS(5, 15, 32)
CLOSE(32)

OPEN(UNIT=33, FILE="./validation/batch_pvsh_rad_cons.dat")
CALL BATCH_PVSH_RAD_CONS(5, 15, 33)
CLOSE(33)

OPEN(UNIT=34, FILE="./validation/batch_pvsh_pol_cons.dat")
CALL BATCH_PVSH_POL_CONS(5, 15, 34)
CLOSE(34)

OPEN(UNIT=35, FILE="./validation/batch_pvsh_tor_cons.dat")
CALL BATCH_PVSH_TOR_CONS(5, 15, 35)
CLOSE(35)

OPEN(UNIT=36, FILE="./validation/batch_vsh_tor_cons.dat")
CALL BATCH_VSH_TOR_CONS(5, 15, 36)
CLOSE(36)

OPEN(UNIT=37, FILE="./validation/batch_vsh_pol_up_cons.dat")
CALL BATCH_VSH_POL_UP_CONS(5, 15, 37)
CLOSE(37)

OPEN(UNIT=38, FILE="./validation/batch_vsh_pol_dn_cons.dat")
CALL BATCH_VSH_POL_DN_CONS(5, 15, 38)
CLOSE(38)

OPEN(UNIT=39, FILE="./validation/pvsh_pol_tor_ortho.dat")
CALL PVSH_POL_TOR_ORTHO(5, 15, 39)
CLOSE(39)

OPEN(UNIT=40, FILE="./validation/vsh_pol_inversion.dat")
CALL VSH_POL_INVERSION(5, 15, 40)
CLOSE(40)

END
